#! /bin/sh

case "$1" in
  start)
    /periodic-display.sh &
    ;;
  stop)
    echo "I can't let you do that."
    ;;
  *)
    echo "Usage: /etc/init.d/periodic-display-init
{start|stop}"
    exit 1
    ;;
esac
exit 0
